name: Purge jsDelivr Cache
on:
  push:
    paths:
      - 'tvbox_Super.json'
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge
        run: curl -s "https://purge.jsdelivr.net/gh/superk521/tvbox-parents@main/tvbox_Super.json"
